spring:
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:lotodb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  error:
    whitelabel:
      enabled: false